server:
  port: 10020

spring:
  profiles:
    active: dev
  application:
    name: magic-bag-order
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=${spring.application.name}&refresh=true
      - nacos:shared-config.yaml?refresh=true

  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 52.77.254.95:8848 # Nacos??????
        group: MAGIC_BAG
      config:
        server-addr: 52.77.254.95:8848 # Nacos??????